### model
model_name_or_path: Qwen2.5-Coder-14B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: opt_5k_vanilla_pure_remove_train
template: qwen
cutoff_len: 16384
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: saves/Qwen2.5-Coder-14B_5k_sft_opt_v3
logging_steps: 1
plot_loss: true
overwrite_output_dir: true
save_only_model: true
save_strategy: epoch

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-06
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb